Update privacy.md
minvws/nl-covid19-notification-app-website pull request #455
Opened 2021-03-11 13:45 UTC by Sijtsma

Typefouten gevonden en aangepast. Hyperlink aangepast zodat deze een linktekst heeft.

2021-03-11 13:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/minvws/nl-covid19-notification-app-website?pullRequest=455) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/minvws/nl-covid19-notification-app-website?pullRequest=455) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/minvws/nl-covid19-notification-app-website?pullRequest=455) it.</sub>

2021-03-11 20:21 UTC, bramd requested changes

2021-03-11 20:21 UTC, bramd commented on privacy.md
> +De DKs worden gedeeld via de Europese Federatieve Gateway Service (EFGS) met andere Europese landen die app hebben met vergelijkbaar beveiligingsniveau en zich aan hebben gesloten bij de EFGS. Aanslu
"die app hebben", moet dit niet zijn "die een app hebben"?

2021-03-12 14:56 UTC, Sijtsma commented on privacy.md
> +De DKs worden gedeeld via de Europese Federatieve Gateway Service (EFGS) met andere Europese landen die app hebben met vergelijkbaar beveiligingsniveau en zich aan hebben gesloten bij de EFGS. Aanslu
Ik heb het aangepast!

2021-03-16 10:08 UTC, bramd approved these changes

2021-03-24 10:19 UTC, anneke commented
Hoi, bedankt voor de toevoeging @Sijtsma ! De typefout was al gecorrigeerd met een nieuwe versie van de privacy statement, maar de suggestie voor de linktekst is een hele goede en nemen we mee.

2021-03-24 10:19 UTC, merged